name: Continues Intigration

on:
  push:
    branches:
      - main

jobs:
  Continues-Integration:
    runs-on: ubantu-latest

    steps:
      - run: echo "CI Actions Begins"
      - name: "Install Dependencys"
        run: npm i
      - name: "Build Process Triggered"
        run: npm run build
